site_name: LogLife

repo_url: https://github.com/jmoraispk/life-bot.git

docs_dir: docs

theme:
  name: material
  palette:
    - scheme: slate
  features:
    - content.image.lightbox
    - navigation.tabs
    - navigation.sections

nav:
  - Home: index.md
  - User Manual:
    - Overview: usage/overview.md
    - Audio Journaling: usage/audio-journaling.md
    - Referrals: usage/referrals.md
    - Managing Goals: usage/managing-goals.md
  - Core Framework:
    - Quickstart: core/quickstart.md
    - Architecture: core/architecture.md
    - WhatsApp Setup: core/whatsapp-setup.md
    - Twilio Setup: core/twilio-setup.md
    - API Reference:
        - Core API: api/backend/core.md
  - App Implementation:
    - Overview: app/overview.md
    - Database: app/database.md
    - Quick Access: developer/quick-access.md
    - API Reference:
        - Routes: api/backend/routes.md
        - Business Logic: api/backend/logic.md
        - Services: api/backend/services.md
        - Database Ops: api/backend/database.md
        - WhatsApp Client: api/whatsapp-client.md

markdown_extensions:
  - toc:
      title: On this page
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

plugins:
  - search
  - glightbox
  - mermaid-zoom
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            docstring_style: google

extra_css:
  - extra_css/theme.css
  - extra_css/mermaid_custom.css

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - extra_js/open_github_new_tab.js
