[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "goal_bot"
version = "0.1.0"
requires-python = "==3.13.2"
description = "Backend for WhatsApp goal tracking bot"
authors = [{name = "Your Name"}]
dependencies = [
    "flask",
]

[tool.aerich]
tortoise_orm = "app.db.config.TORTOISE_ORM"
location = "./app/db/migrations"
src_folder = "./."
